#!/usr/bin/env python3
"""Enable production RTL text support in a UIFlow2 source checkout.

Run this after UIFlow2's ``make submodules`` and ``make patch`` steps, then
build ``BOARD=M5STACK_CoreS3`` normally. The patch is deliberately exact and
idempotent: an upstream configuration change fails loudly instead of producing
a firmware image whose Arabic support is uncertain.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

RELATIVE_LV_CONF = Path("m5stack/cmodules/lv_binding_micropython/lv_conf.h")
RELATIVE_BIDI = Path("m5stack/cmodules/lv_binding_micropython/lvgl/src/misc/lv_bidi.c")
RELATIVE_MANIFEST = Path("m5stack/boards/M5STACK_CoreS3/manifest.py")
RELATIVE_ABI_MODULE = Path("m5stack/libs/translator_rtl.py")
RELATIVE_FONT_DIR = Path("m5stack/components/M5Unified/fonts")
MANIFEST_LINE = 'freeze("$(MPY_DIR)/../m5stack/libs/", "translator_rtl.py")'
ABI_MODULE = """# Generated by the translator UIFlow2 RTL patch.
ABI_VERSION = 2
BIDI = True
ARABIC_SHAPING = True
ARABIC_SOURCE_FONT = "translator_cairo_16"
ARABIC_TRANSLATION_FONT = "translator_cairo_24"
HEBREW_SOURCE_FONT = "translator_noto_hebrew_16"
HEBREW_TRANSLATION_FONT = "translator_noto_hebrew_24"
FONT_LICENSE = "OFL-1.1"
FONT_COPYRIGHTS = (
    "Copyright 2009 The Cairo Project Authors",
    "Copyright 2022 The Noto Project Authors",
)
"""
FEATURES = {
    "LV_FONT_DEJAVU_16_PERSIAN_HEBREW": "1",
    "LV_USE_BIDI": "1",
    "LV_USE_ARABIC_PERSIAN_CHARS": "1",
    # The generated Cairo/Noto subsets are bpp 2 and lv_font_conv compresses
    # those by default, so every one declares bitmap_format = 1
    # (LV_FONT_FMT_TXT_COMPRESSED). UIFlow ships LV_USE_FONT_COMPRESSED 0, and
    # lv_font_get_bitmap_fmt_txt() then returns NULL for every glyph of those
    # fonts behind an LV_LOG_WARN that is itself compiled out. Enable the
    # decompressor so the subsets can actually be drawn.
    "LV_USE_FONT_COMPRESSED": "1",
}
CUSTOM_FONTS = (
    "AlibabaPuHuiTi_CN24",
    "AlibabaSans_JP24",
    "AlibabaSans_KR24",
    "translator_cairo_16",
    "translator_cairo_24",
    "translator_noto_hebrew_16",
    "translator_noto_hebrew_24",
)
FONT_FILES = (
    Path("firmware/fonts/cairo/translator_cairo_16.c"),
    Path("firmware/fonts/cairo/translator_cairo_24.c"),
    Path("firmware/fonts/noto_sans_hebrew/translator_noto_hebrew_16.c"),
    Path("firmware/fonts/noto_sans_hebrew/translator_noto_hebrew_24.c"),
)

# Memory-safety fix for lv_bidi_process_paragraph(), verified on this repo's
# LVGL fork at yharby/lvgl, branch fix/bidi-truncated-utf8.
#
# UIFlow pins an LVGL 9.3 commit in which lv_bidi_process_paragraph() assumes
# `len` ends on an encoded-character boundary. Label line breaking can pass a
# byte count that lands inside a multibyte Arabic or Hebrew character, and
# rtl_reverse() then decodes that trailing character at its full size, so the
# write cursor moves past `len` and lv_memcpy() writes past the output buffer.
#
# LVGL PR #9908 proposed clamping the individual writes. That PR is still open
# with changes requested, because clamping the bytes while callers keep
# advancing by the original run length desynchronizes the text from the
# position map. This backport takes the other route and rejects the unaligned
# length once, before any decoding, so no counter can drift.
BIDI_BACKPORTS = (
    (
        r"""static uint32_t get_txt_len(const char * txt, uint32_t max_len);
""",
        r"""static uint32_t get_txt_len(const char * txt, uint32_t max_len);
static bool is_encoded_len_aligned(const char * txt, uint32_t len);
""",
    ),
    (
        r"""    uint16_t pos_conv_wr;

    if(base_dir == LV_BASE_DIR_AUTO) base_dir = lv_bidi_detect_base_dir(str_in);
""",
        r"""    uint16_t pos_conv_wr;

    /*`len` must not end inside an encoded character. Reordering a truncated
     *character is not possible, and letting the decoder read the whole
     *character would advance the write cursor past `len`. Copy the bounded
     *bytes through unchanged instead, which keeps the output length and the
     *position map consistent with what the caller asked for.*/
    if(!is_encoded_len_aligned(str_in, len)) {
        if(str_out) {
            lv_memmove(str_out, str_in, len);
            str_out[len] = '\0';
        }
        if(pos_conv_out) fill_pos_conv(pos_conv_out, pos_conv_len, 0);
        return;
    }

    if(base_dir == LV_BASE_DIR_AUTO) base_dir = lv_bidi_detect_base_dir(str_in);
""",
    ),
    (
        r"""    if(rd && str_in[rd] != '\0' && rd < len) {
""",
        r"""    if(rd && rd < len && str_in[rd] != '\0') {
""",
    ),
    (
        r"""static void fill_pos_conv(uint16_t * out, uint16_t len, uint16_t index)
""",
        r"""/**
 * Check that `len` bytes of `txt` end on an encoded character boundary.
 * Only the leading byte of each character is read, so this never reads past
 * `txt[len - 1]`.
 * @param txt       the text to check
 * @param len       length in bytes
 * @return          true: `len` ends on a character boundary
 */
static bool is_encoded_len_aligned(const char * txt, uint32_t len)
{
    uint32_t i = 0;

    while(i < len) {
        uint32_t encoded_size = lv_text_encoded_size(&txt[i]);
        if(encoded_size == 0) encoded_size = 1;
        if(encoded_size > len - i) return false;
        i += encoded_size;
    }

    return true;
}

static void fill_pos_conv(uint16_t * out, uint16_t len, uint16_t index)
""",
    ),
)


def set_define(text: str, name: str, value: str) -> str:
    prefix = f"#define {name} "
    matches = [line for line in text.splitlines() if line.startswith(prefix)]
    if len(matches) != 1:
        raise RuntimeError(f"expected one {name} definition, found {len(matches)}")
    old = matches[0]
    suffix = old[len(prefix) :]
    comment = ""
    marker = suffix.find("/*")
    if marker >= 0:
        comment = "  " + suffix[marker:].strip()
    replacement = prefix + value + comment
    return text.replace(old, replacement, 1)


def apply_exact_backport(text: str, old: str, new: str) -> tuple[str, bool]:
    if new in text:
        return text, False
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"LVGL BiDi backport context expected once, found {count}")
    return text.replace(old, new, 1), True


def patch_checkout(checkout: Path) -> bool:
    path = checkout / RELATIVE_LV_CONF
    if not path.is_file():
        raise RuntimeError(f"missing {path}; run UIFlow2 'make submodules' and 'make patch' first")
    original = path.read_text()
    updated = original
    for name, value in FEATURES.items():
        updated = set_define(updated, name, value)
    declarations = " ".join(f"LV_FONT_DECLARE({name})" for name in CUSTOM_FONTS)
    updated = set_define(updated, "LV_FONT_CUSTOM_DECLARE", declarations)
    changed = updated != original
    if changed:
        path.write_text(updated)

    bidi_path = checkout / RELATIVE_BIDI
    if not bidi_path.is_file():
        raise RuntimeError(f"missing pinned LVGL BiDi source: {bidi_path}")
    bidi = bidi_path.read_text()
    bidi_changed = False
    for old, new in BIDI_BACKPORTS:
        bidi, replacement_changed = apply_exact_backport(bidi, old, new)
        bidi_changed = bidi_changed or replacement_changed
    if bidi_changed:
        bidi_path.write_text(bidi)
        changed = True

    manifest_path = checkout / RELATIVE_MANIFEST
    if not manifest_path.is_file():
        raise RuntimeError(f"missing CoreS3 manifest: {manifest_path}")
    manifest = manifest_path.read_text()
    if MANIFEST_LINE not in manifest:
        manifest_path.write_text(manifest.rstrip() + "\n" + MANIFEST_LINE + "\n")
        changed = True

    abi_path = checkout / RELATIVE_ABI_MODULE
    if not abi_path.is_file() or abi_path.read_text() != ABI_MODULE:
        abi_path.write_text(ABI_MODULE)
        changed = True

    source_root = Path(__file__).resolve().parents[1]
    destination_dir = checkout / RELATIVE_FONT_DIR
    if not destination_dir.is_dir():
        raise RuntimeError(f"missing UIFlow2 font directory: {destination_dir}")
    for relative_source in FONT_FILES:
        source = source_root / relative_source
        if not source.is_file():
            raise RuntimeError(f"missing generated font source: {source}")
        destination = destination_dir / source.name
        if not destination.is_file() or destination.read_bytes() != source.read_bytes():
            shutil.copyfile(source, destination)
            changed = True
    return changed


def verify_checkout(checkout: Path) -> None:
    text = (checkout / RELATIVE_LV_CONF).read_text()
    for name, value in FEATURES.items():
        expected = f"#define {name} {value}"
        if expected not in text:
            raise RuntimeError(f"RTL verification failed: {expected!r} not found")
    for name in CUSTOM_FONTS:
        expected = f"LV_FONT_DECLARE({name})"
        if expected not in text:
            raise RuntimeError(f"font declaration missing: {expected}")
    bidi = (checkout / RELATIVE_BIDI).read_text()
    for _old, new in BIDI_BACKPORTS:
        if new not in bidi:
            raise RuntimeError("LVGL BiDi alignment backport is incomplete")
    if MANIFEST_LINE not in (checkout / RELATIVE_MANIFEST).read_text():
        raise RuntimeError("RTL ABI module is not frozen by the CoreS3 manifest")
    if (checkout / RELATIVE_ABI_MODULE).read_text() != ABI_MODULE:
        raise RuntimeError("RTL ABI marker module is missing or stale")
    source_root = Path(__file__).resolve().parents[1]
    for relative_source in FONT_FILES:
        source = source_root / relative_source
        destination = checkout / RELATIVE_FONT_DIR / source.name
        if not destination.is_file() or destination.read_bytes() != source.read_bytes():
            raise RuntimeError(f"firmware font is missing or stale: {source.name}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("checkout", type=Path, help="uiflow-micropython checkout")
    args = parser.parse_args()
    changed = patch_checkout(args.checkout.resolve())
    verify_checkout(args.checkout.resolve())
    state = "patched" if changed else "already enabled"
    print(f"UIFlow2 RTL configuration: {state}")
    print(
        "Enabled LVGL bidi, shaping, BiDi alignment safety backport, Cairo/Noto RTL fonts, and ABI"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
